language: python
os: linux
jobs:
  include:
    - stage: deploy
      script: echo "Starting Pypi build"
      deploy:
        provider: pypi
        username: "__token__"
        password: "$PYPI_TOKEN"
        on:
          tags: true